baseurl = "http://turcuciprian.com/"
languageCode = "en-us"
title = "Turcu Ciprian - My very own personal place in the world"
theme = "casper"

[params]
  description = "Ciprian's Awesome Hugo Site"
  author = "Ciprian Turcu"
