baseurl = "http://turcuciprian.com/"
languageCode = "en-us"
title = "Turcu Ciprian"
theme = "cactus"
#theme git repo: https://github.com/digitalcraftsman/hugo-cactus-theme.git

[params]
  description = "My very own place in the world"
  author = "Ciprian Turcu"
  cover = "images/cover.jpeg"
  logo = "images/logo.jpeg"
  githubName = "turcuciprian"
  twitterName = "turcuciprian"
  facebookName = "turcu.ciprian"


